import sys
import os
import json
from dataclasses import dataclass, field
from PyQt5 import QtWidgets, QtCore
from NodeGraphQt import NodeGraph, BackdropNode

# Импортируем нашу базу данных нод
import nodes_gmod

# ==================== СТИЛИ И ИНТЕРФЕЙС ====================

DARK_THEME = """
QWidget { background-color: #1E1E1E; color: #D4D4D4; font-size: 13px; }
QTreeWidget { background-color: #252526; border: 1px solid #3E3E42; color: #D4D4D4; }
QTreeWidget::item:hover { background-color: #2A2D2E; }
QTreeWidget::item:selected { background-color: #094771; color: #FFFFFF; }
QHeaderView::section { background-color: #2D2D30; color: #FFFFFF; border: none; padding: 5px; }
QSplitter::handle { background-color: #3E3E42; }
QPushButton {
    background-color: #2B712B;
    color: white;
    border: none;
    border-radius: 4px;
    padding: 6px 12px;
    font-weight: bold;
}
QPushButton:hover { background-color: #358C35; }
QPushButton#secondary_btn {
    background-color: #3E3E42;
}
QPushButton#secondary_btn:hover { background-color: #505054; }
"""

# ==================== СТРОГАЯ ТИПИЗАЦИЯ ПОРТОВ ====================

PORT_EXEC = nodes_gmod.PORT_EXEC
PORT_NUMBER = nodes_gmod.PORT_NUMBER
PORT_BOOL = nodes_gmod.PORT_BOOL
PORT_STRING = nodes_gmod.PORT_STRING
PORT_PLAYER = nodes_gmod.PORT_PLAYER
PORT_VECTOR = nodes_gmod.PORT_VECTOR

PORT_COLORS = nodes_gmod.PORT_COLORS

# ==================== КОНТЕКСТ КОМПИЛЯЦИИ ====================

@dataclass
class CompileContext:
    """
    Контекст компиляции цепочки выполнения.
    Хранит информацию о текущих отступах и доступных локальных переменных хука.
    """
    variables: dict = field(default_factory=dict)
    indent: str = '    '

    def indented(self, extra: str = '    ') -> 'CompileContext':
        return CompileContext(variables=self.variables, indent=self.indent + extra)

    def get(self, name: str, fallback: str = 'nil') -> str:
        return self.variables.get(name, fallback)


# ==================== КОМПИЛЯТОР ГРАФА ====================

class BlueprintCompiler:
    def __init__(self, graph):
        self.graph = graph
        self.visited_nodes = set()

    def compile(self) -> str:
        self.visited_nodes.clear()
        
        # Шаг 1: Сканируем граф для поиска всех уникальных названий переменных
        detected_variables = set()
        for node in self.graph.all_nodes():
            # Если нода имеет свойство 'var_name', значит это Set или Get Variable
            if node.get_property('var_name') is not None:
                name = node.get_property('var_name').strip().replace(' ', '_')
                if name:
                    detected_variables.add(name)

        # Шаг 2: Формируем заголовок файла
        lua = '-- Generated by WireBranch Blueprints Editor\n\n'
        
        if detected_variables:
            lua += '-- File-Scoped Script Variables\n'
            for var in sorted(detected_variables):
                lua += f'local {var} = nil\n'
            lua += '\n'

        # Шаг 3: Генерируем хуки
        for node in self.graph.all_nodes():
            if isinstance(node, nodes_gmod.BaseEventNode):
                lua += node.compile_event(self)
        return lua

    def resolve_port_value(self, port, ctx: CompileContext, fallback: str = '0') -> str:
        if not port:
            return fallback
        connections = port.connected_ports()
        if not connections:
            return fallback
            
        source_port = connections[0]
        source_node = source_port.node()
        
        node_id = id(source_node)
        if node_id in self.visited_nodes:
            return fallback
            
        self.visited_nodes.add(node_id)
        try:
            val = source_node.resolve_port_output_value(source_port.name(), self, ctx)
        finally:
            self.visited_nodes.remove(node_id)
            
        return val

    def compile_exec_chain(self, start_port, ctx: CompileContext) -> str:
        if not start_port:
            return ""
        connections = start_port.connected_ports()
        if not connections:
            return ""
            
        target_port = connections[0]
        target_node = target_port.node()
        
        if hasattr(target_node, 'compile_node'):
            return target_node.compile_node(self, ctx)
        return ""


# ==================== ГЛАВНЫЙ ИНТЕРФЕЙС РЕДАКТОРА ====================

ALL_NODE_CLASSES = nodes_gmod.ALL_NODE_CLASSES

class BlueprintEditor(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("WireBranch Blueprint Editor")
        self.resize(1400, 850)

        layout = QtWidgets.QVBoxLayout(self)
        splitter = QtWidgets.QSplitter(QtCore.Qt.Horizontal)
        layout.addWidget(splitter)

        # Библиотека узлов (Слева)
        self.tree = QtWidgets.QTreeWidget()
        self.tree.setHeaderLabel("Available Blueprint Nodes")
        splitter.addWidget(self.tree)

        cats = {
            "Events": QtWidgets.QTreeWidgetItem(self.tree, ["Events"]),
            "Values": QtWidgets.QTreeWidgetItem(self.tree, ["Values"]),
            "Logic": QtWidgets.QTreeWidgetItem(self.tree, ["Logic"]),
            "Actions": QtWidgets.QTreeWidgetItem(self.tree, ["Actions"])
        }

        # Динамически распределяем ноды по категориям
        for cls in ALL_NODE_CLASSES:
            if 'events' in cls.__identifier__:
                parent = cats["Events"]
            elif 'values' in cls.__identifier__:
                parent = cats["Values"]
            elif 'logic' in cls.__identifier__:
                parent = cats["Logic"]
            else:
                parent = cats["Actions"]
            
            item = QtWidgets.QTreeWidgetItem(parent, [cls.NODE_NAME])
            item.setData(0, QtCore.Qt.UserRole, cls)

        self.tree.expandAll()

        # Инициализация и настройка Графа
        self.graph = NodeGraph()
        for node_cls in ALL_NODE_CLASSES:
            self.graph.register_node(node_cls)

        splitter.addWidget(self.graph.widget)

        # Сигналы редактора
        self.graph.port_connected.connect(self.on_port_connected)
        self.graph.widget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.graph.widget.customContextMenuRequested.connect(self.open_graph_context_menu)
        self.tree.itemDoubleClicked.connect(self.spawn_node_from_tree)
        self.graph.node_double_clicked.connect(self.on_node_double_clicked)

        # Горячие клавиши
        QtWidgets.QShortcut(QtCore.Qt.Key_Delete, self, self.delete_selected_nodes)
        QtWidgets.QShortcut(QtCore.Qt.Key_C, self, self.create_comment_from_selection)
        QtWidgets.QShortcut(QtCore.Qt.Key_F2, self, self.rename_selected_comment)

        # Нижняя панель управления
        actions_panel = QtWidgets.QHBoxLayout()
        
        save_btn = QtWidgets.QPushButton("Save Project (JSON)")
        save_btn.setObjectName("secondary_btn")
        save_btn.clicked.connect(self.save_project)
        
        load_btn = QtWidgets.QPushButton("Load Project (JSON)")
        load_btn.setObjectName("secondary_btn")
        load_btn.clicked.connect(self.load_project)
        
        compile_btn = QtWidgets.QPushButton("Compile Graph to Lua")
        compile_btn.clicked.connect(self.compile_graph)

        actions_panel.addWidget(save_btn)
        actions_panel.addWidget(load_btn)
        actions_panel.addSpacing(400)
        actions_panel.addWidget(compile_btn)
        layout.addLayout(actions_panel)

    def on_port_connected(self, port_in, port_out):
        """Контроль строгой типизации при попытке соединить кабели."""
        type_in = getattr(port_in, 'custom_data_type', None)
        type_out = getattr(port_out, 'custom_data_type', None)
        if type_in != type_out:
            port_in.disconnect_from(port_out)

    def spawn_node_from_tree(self, item, column):
        node_cls = item.data(0, QtCore.Qt.UserRole)
        if node_cls:
            node_type = f"{node_cls.__identifier__}.{node_cls.__name__}"
            node = self.graph.create_node(node_type)
            node.set_pos(0, 0)

    def on_node_double_clicked(self, node):
        if isinstance(node, BackdropNode):
            self.edit_comment_text(node)

    def rename_selected_comment(self):
        sel = self.graph.selected_nodes()
        if len(sel) == 1 and isinstance(sel[0], BackdropNode):
            self.edit_comment_text(sel[0])

    def edit_comment_text(self, backdrop_node):
        curr = backdrop_node.get_property('name') or ""
        text, ok = QtWidgets.QInputDialog.getText(self, "Edit Comment", "Text:", QtWidgets.QLineEdit.Normal, curr)
        if ok and text != curr:
            self.graph.begin_undo('Rename Comment')
            backdrop_node.set_property('name', text)
            self.graph.end_undo()

    def create_comment_from_selection(self):
        selected_nodes = self.graph.selected_nodes()
        if not selected_nodes:
            b = self.graph.create_node('nodeGraphQt.nodes.BackdropNode')
            b.set_property('name', 'Comment')
            return

        min_x, min_y = float('inf'), float('inf')
        max_x, max_y = float('-inf'), float('-inf')

        for node in selected_nodes:
            if isinstance(node, BackdropNode): continue
            x, y = node.pos()
            if x < min_x: min_x = x
            if y < min_y: min_y = y
            if (x + 180) > max_x: max_x = x + 180
            if (y + 140) > max_y: max_y = y + 140

        if min_x == float('inf'): return
        
        self.graph.begin_undo('Create Comment')
        b = self.graph.create_node('nodeGraphQt.nodes.BackdropNode', pos=[min_x - 40, min_y - 60])
        b.set_property('name', 'Comment Box')
        b.set_property('width', (max_x - min_x) + 80)
        b.set_property('height', (max_y - min_y) + 100)
        self.graph.end_undo()

    def open_graph_context_menu(self, pos):
        menu = QtWidgets.QMenu(self)
        c_act = menu.addAction("Wrap in Comment (C)")
        d_act = menu.addAction("Delete Selected Nodes")
        act = menu.exec_(self.graph.widget.mapToGlobal(pos))
        if act == d_act: self.delete_selected_nodes()
        elif act == c_act: self.create_comment_from_selection()

    def delete_selected_nodes(self):
        for node in self.graph.selected_nodes():
            self.graph.delete_node(node)

    def save_project(self):
        path, _ = QtWidgets.QFileDialog.getSaveFileName(self, "Save Project", "", "WireBranch Project (*.json)")
        if path:
            self.graph.save_session(path)
            QtWidgets.QMessageBox.information(self, "Success", "Project state saved successfully!")

    def load_project(self):
        path, _ = QtWidgets.QFileDialog.getOpenFileName(self, "Load Project", "", "WireBranch Project (*.json)")
        if path:
            self.graph.load_session(path)
            QtWidgets.QMessageBox.information(self, "Success", "Project state loaded successfully!")

    def compile_graph(self):
        compiler = BlueprintCompiler(self.graph)
        lua_code = compiler.compile()
        out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "generated_script.lua")
        
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(lua_code)
            
        QtWidgets.QMessageBox.information(self, "Success", f"Garry's Mod Lua code compiled to:\n{out_path}")


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    app.setStyleSheet(DARK_THEME)
    window = BlueprintEditor()
    window.show()
    sys.exit(app.exec_())